### ISSUE TITLE
Link (page) Errors.

### ISSUE THREAD

**Issue by Nazneen05x** [Maaike0904/the-client-case#1]
Hoi Maaike! 😊

Je bent echt goed bezig! Je code ziet er interessant uit.

**Feedback:**

Je page link in je about me zetten. Zodat ik kan checken, wat je hebt gedaan. En Wat inspiratie  opdoen hihi.

**Erros**

Je hebt twee erros

![image](https://user-images.githubusercontent.com/112861261/193225529-09bf455b-6d08-4cc5-bf69-ae06e856c1b7.png)

Groet,
Naz

**Comment by Maaike0904** [comment]
Deze feedback heb ik verwerkt :)
