### ISSUE TITLE
Iconen via JavaScript?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Maaike0904/the-client-case#6]
Zijn iconen iets wat je via JavaScript in hoort te laden? Of is HTML of CSS hier een betere plek voor? Denk aan de intentie van je code.

https://github.com/Maaike0904/the-client-case/blob/2b7c9b111673e2071302785a4753696198ff09aa/index.html#L9

**Comment by Maaike0904** [comment]
Zet ik even opzij
