### ISSUE TITLE
Alt attribuut van logo

### ISSUE THREAD

**Issue by KrijnHoetmer** [Maaike0904/the-client-case#7]
Probeer, zeker bij een logo of een andere afbeelding met tekst erin, de tekst uit de afbeelding in het alt attribuut te zetten. Hoe zou je dit element voorlezen aan de telefoon? Dát zet je in het alt attribuut.

https://github.com/Maaike0904/the-client-case/blob/2b7c9b111673e2071302785a4753696198ff09aa/index.html#L37

**Comment by Maaike0904** [comment]
Die heb ik nu vernoemd naar logo vini mini
