### ISSUE TITLE
Checkbox voor navigatie

### ISSUE THREAD

**Issue by KrijnHoetmer** [Maaike0904/the-client-case#8]
Pas op met de checkbox hack voor navigatie. Een checkbox is een formulierelement, niet iets om navigatie te tonen of te verbergen. Ideaal om dit zo via CSS en `:checked` te doen natuurlijk, maar er zijn betere/semantischere manieren.

https://github.com/Maaike0904/the-client-case/blob/2b7c9b111673e2071302785a4753696198ff09aa/index.html#L47-L51

**Comment by Maaike0904** [comment]
Dit zet ik even opzij
